# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Makefile', 'README.md', '_ignore']
markdown: maruku

# configuration required for some pages

domain: pawsnet.github.com
title: PAWS, Public Access Wi-Fi Service
author: Richard Mortier
email: richard.mortier@nottingham.ac.uk

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

google_analytics:
  account: UA-36244686-1

# github:
#   username: ghusername

# disqus:
#   id: disqusid
